# Generated by Django 3.2.4 on 2021-08-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(help_text='Например: https://www.youtube.com/watch?v=jNQXAC9IVRw', verbose_name='Ссылка на Youtube'),
        ),
    ]
